### ISSUE TITLE
Changes Required

### ISSUE THREAD

**Issue by preciousuwhubetine** [vangelif/Portfolio#12]
The following issues were discovered in your code:

https://github.com/vangelif/Portfolio/blob/281ef1d8d02d870a468f1d76224b4f61c3cda956/script.js#L88-L97
- The technologies list for each portfolio item displays only one element at a time. It should display all the technologies used in building the project. Consider changing `technologies = `<li> ` on line 91 to `technologies += `<li> `

https://github.com/vangelif/Portfolio/blob/281ef1d8d02d870a468f1d76224b4f61c3cda956/script.js#L175
- The close popup buttons should be selected with a class of `close-popup`, not an id.

https://github.com/vangelif/Portfolio/blob/281ef1d8d02d870a468f1d76224b4f61c3cda956/script.js#L199
- An error is thrown when the user submits the form. This was caused by the wrong id being set on the input field. The correct id from your html file is `text-box`.
https://github.com/vangelif/Portfolio/blob/281ef1d8d02d870a468f1d76224b4f61c3cda956/index.html#L357-L364

**Comment by vangelif** [comment]
Thank you !
